E-MarcheSolution/E-MarcheWA/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using E_MarcheWA.Helper;
using E_MarcheWA.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace E_MarcheWA.Controllers
{
    public class ArticlesController : Controller
    {
        MarcheAPI _api = new MarcheAPI();
        PaniersController p = new PaniersController();
        private readonly ILogger<ArticlesController> _logger;

        //public articlesController(ILogger<articlesController> logger)
        //{
        //    _logger = logger;
        //}
        public ArticlesController()
        {
            
        }
        public async Task<IActionResult> Index()
        {
            List<ArticleData> articles = new List<ArticleData>();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync("api/articles");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                articles = JsonConvert.DeserializeObject<List<ArticleData>>(result);
            }
            return View(articles);
        }

          
        public async Task<IActionResult> ListArticle()
        {
            List<ArticleData> articles = new List<ArticleData>();
            HttpClient client = _api.Initial();
            //HttpResponseMessage res = await client.GetAsync($"api/articles/{id}");
            HttpResponseMessage res = await client.GetAsync($"api/articles");

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                articles = JsonConvert.DeserializeObject<List<ArticleData>>(result);
            }
            return View(articles);
        }

        public async Task<IActionResult> Details(int id)
        {
            var articles = new ArticleData();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/articles/{id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                articles = JsonConvert.DeserializeObject<ArticleData>(result);
            }
            return View(articles);
        }




        public async Task<IActionResult> Edit(int id)
        {
            var articles = new ArticleData();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/articles/{id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                articles = JsonConvert.DeserializeObject<ArticleData>(result);
            }
            return View(articles);
        }
        [HttpPost]
        public async Task<ArticleData> Edit(ArticleData articles)
        {
            HttpClient client = _api.Initial();

            HttpResponseMessage response = await client.PutAsJsonAsync(
                $"api/articles/{articles.ArticleId}", articles);
            response.EnsureSuccessStatusCode();

            articles = await response.Content.ReadAsAsync<ArticleData>();
            return articles;
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ArticleData articles)
        {
            HttpClient client = _api.Initial();

            //HttpPost
            var postTask = client.PostAsJsonAsync<ArticleData>("api/articles", articles);
            postTask.Wait();
            var result = postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("ListArticle");
            }
            //ViewBag.categorieId = new SelectList(db.Categories, "categorieId", "Nom", categories.CategorieId);
            //ViewBag.smsid = new SelectList(db.Sms, "smsid", "smsid", categories.Smsid);
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            var articles = new ArticleData();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.DeleteAsync($"api/articles/{id}");
            return RedirectToAction("ListArticle");
        }
        //public ActionResult AjoutPanier()
        //{
        //    return View();
        //}
        public async Task<IActionResult> AjoutPanier(int? id)
        {
            //List<ArticleData> articles = new List<ArticleData>();
            ArticleData articles = new ArticleData();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/articles/{id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                articles = JsonConvert.DeserializeObject<ArticleData>(result);
            }
            //foreach (var art in articles)
            //{
                if (articles.ArticleId==id) {
                    PanierData pd = new PanierData
                    {

                        Photo = articles.Photo,
                        Cantite = articles.Cantite,
                        PrixArticle = articles.Prix,
                        ArticleId = articles.ArticleId
                    };
                    p.Create(pd);
                }
            //}
            
            //return View(articles);
            
            return RedirectToAction("Panier", "Paniers");
        }

    }
}

E-MarcheSolution/E-MarcheWA/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using E_MarcheWA.Helper;
using E_MarcheWA.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace E_MarcheWA.Controllers
{
    public class ClientsController : Controller
    {
        MarcheAPI _api = new MarcheAPI();
        private readonly ILogger<ClientsController> _logger;

        public ClientsController(ILogger<ClientsController> logger)
        {
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            List<ClientData> clients = new List<ClientData>();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync("api/clients");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                clients = JsonConvert.DeserializeObject<List<ClientData>>(result);
            }
            return View(clients);
        }

        public ActionResult Connexion_client()
        {
         
                return View();

        }

        [HttpPost]
        public async Task<ActionResult<ClientData>> Connexion_client(ClientData clients)
        {
            HttpClient client = _api.Initial();

            //HttpPost
            HttpResponseMessage postTask = await client.GetAsync("api/clients/LoginClient");
            if (postTask.IsSuccessStatusCode)
            {
                return View("Connexion_client", clients);
            }
            else
            {
                //return RedirectToAction("ListArticleUtilisateur", "Articles");
                return RedirectToAction("ListMarche", "Categories");
            }

            
        }


        //public async Task<IActionResult> Details(int id)
        //{
        //    var clients = new ClientData();
        //    HttpClient client = _api.Initial();
        //    HttpResponseMessage res = await client.GetAsync($"api/clients/{id}");
        //    if (res.IsSuccessStatusCode)
        //    {
        //        var result = res.Content.ReadAsStringAsync().Result;
        //        clients = JsonConvert.DeserializeObject<ClientData>(result);
        //    }
        //    return View(clients);
        //}

        public async Task<IActionResult> Details(int id)
        {
            var clients = new ClientData();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/clients/{id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                clients = JsonConvert.DeserializeObject<ClientData>(result);
            }
            return View(clients);
        }




        public async Task<IActionResult> Edit(int id)
        {
            var clients = new ClientData();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/clients/{id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                clients = JsonConvert.DeserializeObject<ClientData>(result);
            }
            return View(clients);
        }
        
        [HttpPost]
        public async Task<ClientData> Edit(ClientData clients)
        {
            HttpClient client = _api.Initial();

            HttpResponseMessage response = await client.PutAsJsonAsync(
                $"api/clients/{clients.ClientId}", clients);
            response.EnsureSuccessStatusCode();

            clients = await response.Content.ReadAsAsync<ClientData>();
            return clients;
        }

        public ActionResult Inscription_client()
        {
            //CategoriesController cat = new CategoriesController();
            //cat.Index();
            //ViewBag.categorieId = new SelectList(db.Categories, "categorieId", "Nom", clients.CategorieId);
            //ViewBag.smsid = new SelectList(db.Sms, "smsid", "smsid", clients.Smsid);
            return View();
        }

        [HttpPost]
        public IActionResult Inscription_client(ClientData clients)
        {
            HttpClient client = _api.Initial();

            //HttpPost
            var postTask = client.PostAsJsonAsync<ClientData>("api/clients", clients);
            postTask.Wait();
            var result = postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            var clients = new ClientData();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.DeleteAsync($"api/clients/{id}");
            return RedirectToAction("Index");
        }


    }
}

E-MarcheSolution/E-MarcheWA/Controllers/CommercantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using E_MarcheWA.Helper;
using E_MarcheWA.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace E_MarcheWA.Controllers
{
    public class CommercantsController : Controller
    {
        MarcheAPI _api = new MarcheAPI();
        private readonly ILogger<CommercantsController> _logger;

        //public CommercantsController(ILogger<CommercantsController> logger)
        //{
        //    _logger = logger;
        //}
        public CommercantsController()
        {
            
        }
        public async Task<IActionResult> Index()
        {
            List<CommercantData> commercants = new List<CommercantData>();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync("api/commercants");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                commercants = JsonConvert.DeserializeObject<List<CommercantData>>(result);
            }
            return View(commercants);
        }

        public ActionResult Connexion_commercant()
        {
         
                return View();

        }

        [HttpPost]
        public async Task<ActionResult<CommercantData>> Connexion_commercant(CommercantData commercants)
        {
            HttpClient client = _api.Initial();

            //HttpPost
            HttpResponseMessage postTask = await client.GetAsync("api/commercants/LoginClient");
            if (postTask.IsSuccessStatusCode)
            {
                return View("Connexion_client", commercants);
            }
            else
            {
                //return RedirectToAction("ListArticleUtilisateur", "Articles");
                return RedirectToAction("ListMarche", "Categories");
            }

            
        }


        public async Task<IActionResult> Details(int id)
        {
            var commercants = new CommercantData();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/commercants/{id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                commercants = JsonConvert.DeserializeObject<CommercantData>(result);
            }
            return View(commercants);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var commercants = new CommercantData();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/commercants/{id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                commercants = JsonConvert.DeserializeObject<CommercantData>(result);
            }
            return View(commercants);
        }
        [HttpPost]
        public async Task<CommercantData> Edit(CommercantData commercants)
        {
            HttpClient client = _api.Initial();

            HttpResponseMessage response = await client.PutAsJsonAsync(
                $"api/commercants/{commercants.CommercantId}", commercants);
            response.EnsureSuccessStatusCode();

            commercants = await response.Content.ReadAsAsync<CommercantData>();
            return commercants;
        }

        public ActionResult Inscription_commercant()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Inscription_commercant(CommercantData commercants)
        {
            HttpClient client = _api.Initial();

            //HttpPost
            var postTask = client.PostAsJsonAsync<CommercantData>("api/commercants", commercants);
            postTask.Wait();
            var result = postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            //ViewBag.categorieId = new SelectList(db.Categories, "categorieId", "Nom", categories.CategorieId);
            //ViewBag.smsid = new SelectList(db.Sms, "smsid", "smsid", categories.Smsid);
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            var commercants = new CommercantData();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.DeleteAsync($"api/commercants/{id}");
            return RedirectToAction("Index");
        }


    }
}

E-MarcheSolution/E-MarcheWA/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using E_MarcheWA.Models;

namespace E_MarcheWA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

E-MarcheSolution/E-MarcheWA/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@*<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>*@

    <div class="row">
        <body style="background-color: #60C1AE;">
            <div style="text-align:center">
                <h1 style="margin-top: 40px"> Clic & Collect </h1>
                @*<p>
                Un marché virtuel pour faciliter vos achats
            </p>*@
                <img class=img-responsive style="max-width:100%;height:auto;margin-top: 120px;margin-left:120px" src="../images/logo3C.jpg" alt="logo3">
                @*C:\Users\cherif\source\repos\NET5\E-MarcheSolution\E-MarcheWA\wwwroot\lib\bootstrap\dist\css
            C:\Users\cherif\source\repos\Maches_Deconfines_Sulution_V1\Maches_Deconfines\Content*@

            </div>
            <br /><br /> <br /><br />
            @*@if (Session["siren"] == null && Session["nom"] == null)
        {*@

            <div class="row">
                <div class="col-md-6">
                    <div class="col-md-8">
                        <span class="text-center"><h3 class="card-header" style="background-color: #C2C3C7">Commerçant</h3></span>
                        <img style="height: 200px; width: 100%; display: block;" src="../images/logoSelle.jpg" alt="Card image">
                        <div class="card-body">
                            <p class="card-text">Vous êtes artisan ou commerçant.Vous voulez vous raprocher de vos client,  Vous avez l'ambition de ....</p>
                        </div>
                        <div class="text-center">
                            <div class="card-body">
                                <button type="button" class="btn btn-secondary">@Html.ActionLink("Inscription", "Inscription_commercant", "Commercants", new{ @class="my-class" })</button>
                                <button type="button" class="btn btn-secondary">@Html.ActionLink("Connexion", "Connexion_commercant", "Commercants", new{ @class="my-class" })</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-md-8">
                        <span class="text-center"><h3 class="card-header" style="background-color: #C2C3C7">Client</h3></span>
                        <img style="height: 200px; width: 100%; display: block;" src="../images/logoCost.png" alt="Card image">
                        <div class="card-body">
                            <p class="card-text">Vous êtes à la rechrehce d'un marché, d'un produit. Vous voulez faire vos courses sans ce depalcer de chez vous ou de votre travail.</p>
                        </div>
                        <div class="text-center">
                            <div class="card-body">
                                <button type="button" class="btn btn-secondary">@Html.ActionLink("Inscription", "Inscription_client", "Clients", new{ @class="my-class" })</button>
                                <button type="button" class="btn btn-secondary">@Html.ActionLink("Connexion", "Connexion_client", "Clients", new{ @class="my-class" })</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @*}*@
            @*else if (Session["siren"] == null && Session["nom"] != null)
        {
            <div class="row" style="text-align:center;max-width:100%;height:auto;">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <span class="text-center"><h3 class="card-header" style="background-color: #C2C3C7">Votre espace client</h3></span>
                        <a href="@Url.Action("ListArticleUtilisateur", "Articles")">
                            <img style="height: 200px; width: 100%; display: block;" src="../Content/logoCost.png" alt="Card image">
                        </a>
                    </div>*@

            @*</div>
                <div class="col-md-4"></div>

            </div>
        }
        else if (Session["siren"] != null && Session["nom"] != null)
        {
            <div class="row" style="text-align:center;max-width:100%;height:auto;">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <span class="text-center"><h3 class="card-header" style="background-color: #C2C3C7">Votre espace Commerçant</h3></span>
                        <a href="@Url.Action("ListMarche", "Categories")">
                            <img style="height: 200px; width: 100%; display: block;" src="../Content/logoSelle.jpg" alt="Card image">
                        </a>
                    </div>

                </div>
                <div class="col-md-4"></div>
            </div>
        }*@
        </body>
    </div>